"""
LangGraph shared state schema.

Defines the ``WorkflowState`` TypedDict consumed by all graph nodes and
conditional edges.  Every field is optional (except the initial inputs) so
that partial state can flow through the graph incrementally.

As of the App Registry upgrade the state uses a generic actor model
(``actor_id``, ``actor_type``, ``actor_context``) instead of the previous
student-specific fields.  Backward-compatible aliases ``student_id`` and
``student_data`` are kept during the migration period but should not be
used in new code.
"""


from __future__ import annotations

from typing import Any, Dict, List, Optional
from typing_extensions import TypedDict


class WorkflowState(TypedDict, total=False):
    """Shared state passed between LangGraph nodes.

    Fields:
        app_id:             Application that initiated this workflow.
        actor_id:           The actor (student, staff, customer) this workflow
                            is serving.  Replaces the former ``student_id``.
        actor_type:         Actor type discriminator (``"student"`` | ``"staff"``
                            | ``"customer"`` | ``"system"``).
        actor_context:      App-specific actor data (student record, ticket,
                            payment, etc.).  Replaces the former ``student_data``.
        user_input:         The raw question / message from the actor.
        force_workflow:     Optional override to bypass classification.
        detected_workflow:  Workflow label from the classifier (``"grade_inquiry"``,
                            ``"enrollment"``, ``"general"``, etc.).
        context:            Merged context dict (Redis + pgvector results).
        tool_calls:         Audit trail of each tool invoked during workflow
                            execution.
        llm_response:       Final response generated by the smart model.
        cache_hit:          Whether the response was served from semantic cache.
        token_usage:        Accumulated token usage from all LLM calls in this
                            workflow run.
        error:              Error message if any node fails.
        metadata:           App-specific pass-through data.

        student_id:         **Deprecated** — alias for ``actor_id``.
        student_data:       **Deprecated** — alias for ``actor_context``.
    """

    # ── Generic actor fields ────────────────────────────────────────────
    app_id: Optional[str]
    actor_id: str
    actor_type: Optional[str]
    actor_context: Optional[Dict[str, Any]]
    user_input: str
    session_id: Optional[str]
    force_workflow: Optional[str]
    detected_workflow: Optional[str]
    context: Optional[Dict[str, Any]]
    rag_context: Optional[List[Dict[str, Any]]]
    answer_confidence: Optional[float]
    retrieval_debug: Optional[Dict[str, Any]]
    query_embedding: Optional[List[float]]
    rag_query_embedding: Optional[List[float]]
    tool_calls: Optional[List[Dict[str, Any]]]
    cache_hit: Optional[bool]
    token_usage: Optional[Dict[str, Any]]
    error: Optional[str]
    metadata: Optional[Dict[str, Any]]
    llm_response: Optional[str]
    lead_progress: Optional[Dict[str, Any]]
    verified_phone: Optional[str]

    # ── Backward-compatible aliases (deprecated) ────────────────────────
    student_id: Optional[str]
    student_data: Optional[Dict[str, Any]]
